---
- name: Install nginx
  sudo: true
  yum: name=nginx state=present

- name: Copy redirect configuration
  sudo: true
  template: src=swb-redirect.conf dest=/etc/nginx/conf.d/swb-redirect.conf
  tags: nginx_conf

- name: Copy nginx http configuration
  sudo: true
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  tags: nginx_conf

- name: Copy nginx site configuration 
  sudo: true
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
  tags: nginx_conf
